from . import mrp_obs
from . import sale_line_obs
from . import mrp_workorder
from . import stock_picking
from . import purchase_order
from . import sale_order
from . import crm_claim
from . import sale_order_project
from . import product_product
from . import account_move
from . import account_move_line
from . import res_company
from . import account_payment_order